### GET request to example server
GET http://localhost:3000

### GET ALL
GET localhost:3000/api/characters

### GET ID
GET http://localhost:3000/api/characters/8


### GET seacrh and query
GET localhost:3000/api/characters?species=humanoid


