### GET request to example server
GET http://localhost:3000

### GET ALL
GET localhost:3000/api/characters

### GET ID
GET http://localhost:3000/api/characters/8

### GET search and query
GET http://localhost:3000/api/characters?
    species=humanoid

### GET location by id
GET http://localhost:3000/api/location/3
